local hashes = require("game.core.hashes")

local controls, credits

local function show()
	
end

local function hide()
	gui.set_enabled(gui.get_node("root"), false)
end

function init(self)
	msg.post(".", "acquire_input_focus")
	
	self.enabled = true
end

function on_input(self, action_id, action)
	if not self.enabled then return end
	
	if action_id == hashes.ACTION then
		hide()
		msg.post("#menu", "show")
		self.enabled = false
	end
end
